dgswem_src = files([
'DG_hydro_timestep.F',
'DG_sed_timestep.F',
'DG_timestep.F',
'LDG_hydro.F',
'adcirc.F',
'calc_normal.F',
'cfl.F',
'cfl_init.F',
'create_edge_data.F',
'cstart.F',
'detector.F',
'dg.F',
'diff45_41.F',
'ebarrier_edge_hydro.F',
'edge_int_hydro.F',
'edge_int_sed.F',
'first_loop.F',
'flow_edge_hydro.F',
'flow_edge_sed.F',
'func_H.F',
'func_H_x.F',
'func_H_y.F',
'func_qx.F',
'func_qx_t.F',
'func_qx_x.F',
'func_qx_y.F',
'func_qy.F',
'func_qy_t.F',
'func_qy_x.F',
'func_qy_y.F',
'func_sx.F',
'func_sy.F',
'global.F',
'global_3dvs.F',
'harm.F',
'hstart.F',
'ibarrier_edge_hydro.F',
'internal_edge_hydro.F',
'internal_edge_sed.F',
'land_edge_hydro.F',
'land_edge_sed.F',
'lund_formula.F',
'met_forcing.F',
'modified_wave_friction.F',
'nodalattr.F',
'numerical_flux.F',
'ocean_edge_hydro.F',
'ocean_edge_hydro_post.F',
'ocean_edge_sed.F',
'ocean_flow_edge_hydro.F',
'orthobasis_area.F',
'orthobasis_edge.F',
'owiwind.F',
'pdg_debug.F',
'prep_DG.F',
'prep_sed.F',
'prep_slopelim.F',
'quad_pts_area.F',
'quad_pts_edge.F',
'radiation_edge_hydro.F',
'read_input.F',
'reset_lts.F',
'rhs_dg_hydro.F',
'rhs_dg_sed.F',
'second_loop.F',
'sed.F',
'sizes.F',
'slopelimiter.F',
'sta_basis.F',
'tidal_potential.F',
'wetdry.F',
'wind.F',
'write_results.F'
])


mpi_handlers = files(['messenger_new.F', 'messenger_node_new.F'])
