!c To be use with internal_edge_hydro.F
!c created by DW
MODULE INTERNAL_EDGE_LOCALDAT
   USE DG
   USE GLOBAL
   
!C............ DW      
   USE AltMathUtils
!C............
   
   IMPLICIT NONE
   
   INTEGER:: NDRYEDGE
   
   INTEGER, ALLOCATABLE:: DRYEDGEMARK(:)
   LOGICAL, ALLOCATABLE:: WETEDGEMARK(:) 
   REAL(SZ), ALLOCATABLE:: F_HAT_VALINT(:,:)
   REAL(SZ), ALLOCATABLE:: G_HAT_VALINT(:,:)
   REAL(SZ), ALLOCATABLE:: H_HAT_VALINT(:,:)

   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: LZ_XX_IN_VEC, LZ_XY_IN_VEC
   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: LZ_YX_IN_VEC, LZ_YY_IN_VEC 

   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: LZ_XX_EX_VEC, LZ_XY_EX_VEC
   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: LZ_YX_EX_VEC, LZ_YY_EX_VEC 
      
   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: ZE_IN_VEC, ZE_EX_VEC
   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: QX_IN_VEC, QX_EX_VEC
   REAL(SZ), ALLOCATABLE, DIMENSION(:,:):: QY_IN_VEC, QY_EX_VEC
   
   INTEGER, ALLOCATABLE, DIMENSION(:,:):: SORTEDNIEDNARR
   INTEGER, ALLOCATABLE, DIMENSION(:):: SORTEDNIEDNVEC
   
 CONTAINS

    SUBROUTINE INITIALIZE_EDGE_INTEG_LOCALDAT( )
      IMPLICIT NONE 
      
      INTEGER:: MEDGEPT
      LOGICAL, save:: first = .true. 
      INTEGER, ALLOCATABLE, DIMENSION(:,:):: SORTEDNIEDNTMP
      INTEGER:: II
      
      MEDGEPT = MAXVAL(NEGP)
      
      IF ( .NOT. ALLOCATED(F_HAT_VALINT) ) THEN
        ALLOCATE( F_HAT_VALINT(MEDGEPT, NIEDS) ) ;
        ALLOCATE( G_HAT_VALINT(MEDGEPT, NIEDS) ) ;
        ALLOCATE( H_HAT_VALINT(MEDGEPT, NIEDS) ) ;
      END IF
      F_HAT_VALINT = 0.D0 ;
      G_HAT_VALINT = 0.D0 ;
      H_HAT_VALINT = 0.D0 ;
            
      IF ( .NOT. ALLOCATED(ZE_IN_VEC) ) THEN
        ALLOCATE( ZE_IN_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( QX_IN_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( QY_IN_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( ZE_EX_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( QX_EX_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( QY_EX_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( LZ_XX_IN_VEC(MEDGEPT,NIEDS) ) ; 
        ALLOCATE( LZ_XY_IN_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( LZ_YX_IN_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( LZ_YY_IN_VEC(MEDGEPT,NIEDS) ) ; 
        ALLOCATE( LZ_XX_EX_VEC(MEDGEPT,NIEDS) ) ; 
        ALLOCATE( LZ_XY_EX_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( LZ_YX_EX_VEC(MEDGEPT,NIEDS) ) ;
        ALLOCATE( LZ_YY_EX_VEC(MEDGEPT,NIEDS) ) ;          
      END IF
      ZE_IN_VEC = 0.D0 ; ZE_EX_VEC = 0.D0 ;
      QX_IN_VEC = 0.D0 ; QX_EX_VEC = 0.D0 ;
      QY_IN_VEC = 0.D0 ; QY_EX_VEC = 0.D0 ;
      LZ_XX_IN_VEC = 0.D0 ; LZ_XX_EX_VEC = 0.D0 ;
      LZ_XY_IN_VEC = 0.D0 ; LZ_XY_EX_VEC = 0.D0 ;
      LZ_YX_IN_VEC = 0.D0 ; LZ_YX_EX_VEC = 0.D0
      LZ_YY_IN_VEC = 0.D0 ; LZ_YY_EX_VEC = 0.D0
      
      IF ( .NOT. ALLOCATED(DRYEDGEMARK) ) THEN
         ALLOCATE( DRYEDGEMARK(NIEDS) ) ;
      END IF
      DRYEDGEMARK = 0 ;
      NDRYEDGE = 0 ; 
      
      IF ( .NOT. ALLOCATED(WETEDGEMARK) ) THEN
        ALLOCATE( WETEDGEMARK(NIEDS) ) ;
        
        ALLOCATE( SORTEDNIEDNVEC(NIEDS) ) ; 
        ALLOCATE( SORTEDNIEDNARR(-NIEDS:NIEDS,2) ) ; 
      END IF
      WETEDGEMARK = .TRUE. ;
      
      !c Sort the vector NIEDN
      IF ( FIRST ) THEN
        SORTEDNIEDNARR = 0 ;
        SORTEDNIEDNARR(1:NIEDS,1) = NIEDN(1:NIEDS) ;
        SORTEDNIEDNARR(1:NIEDS,2) = (/ (II, II = 1, NIEDS) /)
            
        CALL IHashSort( SORTEDNIEDNARR, NIEDS ) ;        
        
        SORTEDNIEDNVEC = SORTEDNIEDNARR(1:NIEDS,1) ;
        
        FIRST = .FALSE. ; 
      END IF
        
      RETURN ;
   END SUBROUTINE INITIALIZE_EDGE_INTEG_LOCALDAT
      
END MODULE INTERNAL_EDGE_LOCALDAT